Feature/mylook 157/borrar tienda
myLook2018/myLook pull request #104
Opened 2019-06-01 23:38 UTC by A-Donato

parece mucho, pero el inteligente del ui metio un 'format code' y se movieron cosas. Lo unico que habria que mirar es el index.js

2019-06-02 02:34 UTC, rj-vicente submitted a review, later dismissed

2019-06-04 00:52 UTC, GisiGimenez submitted a review, later dismissed
+1 Porque no tengo idea Web 👍

2019-06-04 00:52 UTC, GisiGimenez commented on web/functions/lib/index.js
> +});
Que pasa si falla algun borrado intermedio? se continua hasta al final? o queda inconsistente la BD?

2019-06-04 01:05 UTC, A-Donato commented on web/functions/lib/index.js
> +});
como dice la cabecera, falla y es posible que queden datos inconcistentes. Donde explote, va a frenar. Durante el proceso de gestacion de ese metodo de catorce millones de lineas, tuve que dejar muertos por el camino. Pero anda, tranquila, no debberia explotar a menos que algo le pase a firebase

2019-06-04 01:08 UTC, GisiGimenez commented on web/functions/lib/index.js
> +});
jajajajajajajjaja ok.... es para tener en cuenta... SI mostramos esto en algun momento, a algun profe, que sea una tienda que no este asociada A NADA

2019-06-04 03:52 UTC, ochan12 requested changes
Sorry @A-Donato

2019-06-04 03:52 UTC, ochan12 commented on web/functions/lib/index.js
> +      var deleteRecomendations = admin.firestore().collection('requestRecommendations').where('storeName', '==', storeName);
Acá debería ser algo como
```
for answer in request.answers:
    if answer.storeName == storeName:
        BOOOOMMMMM!!!!!!
```

2019-06-04 20:04 UTC, rj-vicente commented on web/src/app/orchestrator/orchestrator.component.ts
> +        this.dataServide.cleanCache();
nice "servide" y "loged"

2019-06-05 23:39 UTC, A-Donato commented on web/src/app/orchestrator/orchestrator.component.ts
> +        this.dataServide.cleanCache();
obveo pa

2019-06-14 20:18 UTC, M-Exequiel approved these changes

2019-08-04 23:13 UTC, GisiGimenez commented
@A-Donato esto sigue vivo?

2019-08-05 22:44 UTC, A-Donato commented
> 
> 
> @A-Donato esto sigue vivo?

obveamente, igual prefiero no mergear hasta definir eso de que si las recomendaciones mueren o no

2019-08-11 05:02 UTC, GisiGimenez commented
@GisiGimenez si no me tagueas no me entero.... ajjajaj ok, te apruebo por las dudas

2019-08-11 05:02 UTC, GisiGimenez approved these changes

2019-10-11 04:08 UTC, closed without merging