US 227 y 228
myLook2018/myLook pull request #150
Opened 2019-10-16 17:24 UTC by ochan12

Cambios de UI en Nueva Solicitud
Cartel de crea una Nueva Solicitud cuando están vacías
Color en el DatePickerDialog
Cambios UI en Recomendaciones
Cámara funcionando
[app-debug.zip](https://github.com/myLook2018/myLook/files/3735595/app-debug.zip)

2019-10-18 20:56 UTC, A-Donato commented
@ochan12 che ya esta agregado lo que comento rodri? de sacar los labels de los botones de la camara?

2019-10-19 23:35 UTC, GisiGimenez reviewed
Se ve mal en mi celu y si hago click en talle me salen las categorias
SI cargas una solicitud sin Talle o Categoria, creo que no deberias ver los labels en el detalle de la solicitud
Habia que sacar el fab y poner el "+" como un menu en el toolbar. no estaba en la historia pero lo hablamos cuando refinamos... zoriii

2019-10-19 23:35 UTC, GisiGimenez commented on mobile/app/src/main/res/layout/activity_request_recommendation_add_desc.xml
> +                    app:menu_fab_hide_animation="@anim/no_spin_animation"
Esto es un xml? porque no lo subiste y no puedo buildear

2019-10-19 23:35 UTC, GisiGimenez commented on mobile/app/src/main/res/layout/activity_request_recommendation.xml
> +                    android:layout_height="98dp"
esto no depende mucho del celu?

2019-10-19 23:35 UTC, GisiGimenez commented on mobile/app/src/main/res/layout/answer_card.xml
> +                android:visibility="visible"
esta es gone, porque se usa en los post del destacado

2019-10-19 23:35 UTC, GisiGimenez commented on mobile/app/src/main/res/layout/answer_card.xml
>  <?xml version="1.0" encoding="utf-8"?>
Se usa ppara los post de destacados este xml... seguramente entre en conflictos con mis cambios

2019-10-19 23:36 UTC, GisiGimenez commented on mobile/app/src/main/res/layout/answer_card.xml
> +            <TextView
Esta deberia ir gon y ponerse visible en runtime, porque en posts destacados no va

2019-10-20 15:50 UTC, ochan12 commented on mobile/app/src/main/res/layout/activity_request_recommendation_add_desc.xml
> +                    app:menu_fab_hide_animation="@anim/no_spin_animation"
@GisiGimenez Era un xml para ver si podía hacer que no gire el fab, pero ya lo saque

2019-10-20 15:55 UTC, ochan12 commented on mobile/app/src/main/res/layout/activity_request_recommendation.xml
> +                    android:layout_height="98dp"
@GisiGimenez Estaba así

2019-10-21 02:51 UTC, ochan12 commented
Meti los cambios de UI
Cambie el manejo de sacar/elegir y recortar foto lo haga la librería directamente
Metí limites en los campos
Color del Calendario
Hacer visible o no los labels de Size y Category dependiendo si tienen
@A-Donato @GisiGimenez @M-Exequiel @rj-vicente

2019-10-21 02:55 UTC, A-Donato submitted a review, later dismissed
Skeree

2019-10-23 23:21 UTC, rj-vicente submitted a review, later dismissed

2019-10-23 23:43 UTC, GisiGimenez requested changes
El activity nueva solicitud tiene que ser un scroll view, no se ven las opciones, talle y categoria
Hay un crash cuando sacas la foto, el log dice "Process 4739 terminated." y desp cuando envias crashea la app en el celu,
Tambien los textos tienen mal las constraints porque el titulo te pisa la foto, o se queda atras, el talle se queda encima de la categoria
Y el label "tu calificacion" en las answer tiene que empezar gone
Y acordate de sacar el fab por el signo mas arriba

2019-10-23 23:43 UTC, GisiGimenez commented on web/functions/lib/index.js
>      const newPublication = snap.after.data();
@A-Donato vio los cambios de este archivo?

2019-10-23 23:43 UTC, GisiGimenez commented on mobile/app/src/main/res/layout/answer_card.xml
> +            <TextView
@ochan12 HOLAAAAAAAA

2019-10-24 01:49 UTC, ochan12 commented on web/functions/lib/index.js
>      const newPublication = snap.after.data();
@GisiGimenez Es una nueva function, y deployamos functions individualemente, no le cambie nada de las otras

2019-10-24 22:26 UTC, A-Donato submitted a review, later dismissed
![imagen](https://user-images.githubusercontent.com/27789840/67529975-1cc86a80-f694-11e9-8b9b-249d012a7591.png)

2019-10-24 23:45 UTC, ochan12 commented
@GisiGimenez @rj-vicente @M-Exequiel

2019-10-24 23:48 UTC, GisiGimenez submitted a review, later dismissed

2019-10-25 00:05 UTC, merged