Sprint 22 gise -> De to, toditooo
myLook2018/myLook pull request #159
Opened 2019-10-28 02:26 UTC by GisiGimenez

- Bug-052-Cambio de nombre
- Validacion DNI que no exista y cant caracteres correcto, validacion de email con caracteres raros
- nombre de las acciones en los dialogs a pedido de @rj-vicente 
- arreglo en las suscripciones, fotos de perfil circulares, share nuevo en perfiles
- Dejo linda card de answers y posts
- Nueva difusion con cambios de ui (copie a telegram)
- notificaciones lindas (con divider y fonfo blanco)
- Arreglo bug de notificaciones repetidas
- saco refresh en el activity del buscador y bug con articulos duplicados
- US-232-Cambio UI de opciones destacadas

2019-10-28 02:28 UTC, A-Donato requested changes
nah yo hago pr por historia, anda a la mierda

2019-10-29 17:24 UTC, ochan12 approved these changes
:gem:

2019-10-29 23:22 UTC, A-Donato approved these changes
![imagen](https://user-images.githubusercontent.com/27789840/67816780-d014d300-fa89-11e9-9816-d9bec0c5e13a.png)

2019-10-29 23:33 UTC, rj-vicente approved these changes

2019-10-30 23:40 UTC, merged