Feature/ml 249/visualizar cupones
myLook2018/myLook pull request #161
Opened 2019-10-30 04:51 UTC by ochan12

Flujo de visualizar lista de mis cupones y cupones individuales
Ver cupones en Centro de Notificaciones
Abrir cupones desde Centro de notificaciones
Cloud Function FCM para Cupones
Abrir Usuarios destacados desde notificaciones
Cloud Function de crear campaña

2019-10-31 00:43 UTC, A-Donato approved these changes
Si no la reviso, no tiene errores
![imagen](https://user-images.githubusercontent.com/27789840/67909519-4e42a980-fb5e-11e9-9ec2-5c9cdb00879f.png)

2019-10-31 02:04 UTC, GisiGimenez requested changes
Cuando entras a mis cupones y no tenes ninguno, te queda girando el spinner por y para siempre
Hay un crash cuando volves atras desde mis cupones, te marque en los comments

2019-10-31 02:04 UTC, GisiGimenez commented on mobile/app/src/main/java/com/mylook/mylook/profile/AccountActivity.java
> +            startActivityForResult(intent,1);
Este request code ya esta usado, defini otro como constante, si no crashea cuando vuelve porque entra por el request==1 y pide datos que no tiene

2019-10-31 02:04 UTC, GisiGimenez commented on mobile/app/src/main/java/com/mylook/mylook/coupon/MyCoupons.java
> +public class MyCoupons extends AppCompatActivity {
MyCouponsActivity

2019-10-31 02:04 UTC, GisiGimenez commented on mobile/app/src/main/java/com/mylook/mylook/coupon/MyCoupons.java
> +            for (DocumentSnapshot doc : l.getDocuments()) {
if l!= null (?

2019-10-31 02:04 UTC, GisiGimenez commented on mobile/app/src/main/java/com/mylook/mylook/coupon/MyCoupons.java
> +        myCoupons.setLayoutManager(new LinearLayoutManager(mContext));
este codigo esta en initRecyclerView()

2019-10-31 02:04 UTC, GisiGimenez commented on mobile/app/src/main/java/com/mylook/mylook/profile/AccountActivity.java
> +            startActivityForResult(intent,1);
despues de ver MyCoupon.class no devolves ningun result, asique mejor cambia por startActivity :)

2019-11-01 23:23 UTC, ochan12 commented on mobile/app/src/main/java/com/mylook/mylook/profile/AccountActivity.java
> +            startActivityForResult(intent,1);
Me la re mande ahi, no se que onda.

2019-11-01 23:23 UTC, ochan12 commented on mobile/app/src/main/java/com/mylook/mylook/coupon/MyCoupons.java
> +            for (DocumentSnapshot doc : l.getDocuments()) {
Por  ? @GisiGimenez

2019-11-01 23:24 UTC, ochan12 commented on mobile/app/src/main/java/com/mylook/mylook/coupon/MyCoupons.java
> +public class MyCoupons extends AppCompatActivity {
:expressionless:

2019-11-06 01:39 UTC, rj-vicente approved these changes
apruebo sin saber si ya esta resuelto el problema que marco gise... yep, no lo lei, perdon

2019-11-07 01:47 UTC, GisiGimenez approved these changes

2019-11-07 02:44 UTC, A-Donato commented
@ochan12 tai para mergiar https://i.giphy.com/media/cFkiFMDg3iFoI/giphy.webp

2019-11-07 02:44 UTC, A-Donato commented
se banca gifs? 
![imagen](https://user-images.githubusercontent.com/27789840/68355870-6e8adf00-00ef-11ea-9b0a-9e1a040a380c.png)

2019-11-07 02:45 UTC, A-Donato commented
para nada

2019-11-07 11:17 UTC, merged